//
//  CheckPrompt.swift
//  ImageAI
//
//  Created by DoanhMac on 14/3/25.
//
import Foundation
import SwiftUI

class CheckPrompt {
    static let forbiddenKeywordsOri : [String] = [
         "dirty woman",
         "0 years old",
         "1 years old",
         "2 years old",
         "3 years old",
         "4 years old",
         "5 years old",
         "6 years old",
         "7 years old",
         "8 years old",
         "9 years old",
         "10 years old",
         "11 years old",
         "12 years old",
         "13 years old",
         "14 years old",
         "15 years old",
         "16 years old",
         "17 years old",
         "0 yo",
         "1 yo",
         "2 yo",
         "3 yo",
         "4 yo",
         "5 yo",
         "6 yo",
         "7 yo",
         "8 yo",
         "9 yo",
         "10 yo",
         "11 yo",
         "12 yo",
         "13 yo",
         "14 yo",
         "15 yo",
         "16 yo",
         "17 yo",
         "painfully killed",
         "cock",
         "deepthroat",
         "dick",
         "cumshot",
         "wet",
         "fuck",
         "sperm",
         "naked",
         "ass",
         "tits",
         "fingering",
         "masturbate",
         "bitch",
         "blowjob",
         "prostitute",
         "shit",
         "bullshit",
         "dumbass",
         "dickhead",
         "pussy",
         "piss",
         "asshole",
         "boobs",
         "butt",
         "booty",
         "dildo",
         "erection",
         "foreskin",
         "gag",
         "handjob",
         "nude",
         "penis",
         "porn",
         "vibrator",
         "viagra",
         "virgin",
         "vagina",
         "vulva",
         "threesome",
         "orgy",
         "bdsm",
         "hickey",
         "condom",
         "sexting",
         "testicles",
         "anal",
         "bareback",
         "bukkake",
         "creampie",
         "stripper",
         "strap-on",
         "clitoris",
         "cowgirl",
         "fleshlight",
         "contraceptive",
         "lingerie",
         "milf",
         "wank",
         "oral",
         "sucking",
         "straddle",
         "orgasm",
         "slut",
         "cumming",
         "ode",
         "prick",
         "cunt",
         "bastard",
         "faggot",
         "anus",
         "sex",
         "arse",
         "ballsack",
         "biatch",
         "bollock",
         "bollok",
         "boner",
         "boob",
         "bugger",
         "buttplug",
         "coon",
         "fag",
         "feck",
         "fellate",
         "fellatio",
         "felching",
         "fuсk",
         "fudgepacker",
         "homo",
         "jizz",
         "knobend",
         "labia",
         "lmao",
         "lmfao",
         "muff",
         "nigger",
         "nigga",
         "poop",
         "pube",
         "scrotum",
         "sh1t",
         "smegma",
         "spunk",
         "tit",
         "turd",
         "twat",
         "whore",
         "cocks",
         "deepthroats",
         "dicks",
         "cumshots",
         "fucks",
         "sperms",
         "asses",
         "masturbation",
         "bitches",
         "blowjobs",
         "prostitutes",
         "shits",
         "bullshits",
         "dickheads",
         "pussys",
         "pisssing",
         "assholes",
         "butts",
         "dildos",
         "erections",
         "foreskins",
         "gags",
         "handjobs",
         "nudes",
         "penises",
         "vibrators",
         "virgins",
         "vaginas",
         "vulvas",
         "threesomes",
         "orgys",
         "bdsms",
         "hickeys",
         "condoms",
         "sextings",
         "anals",
         "barebacks",
         "bukkakes",
         "creampies",
         "strippers",
         "strap-ons",
         "clitoriss",
         "cowgirls",
         "fleshlights",
         "contraceptives",
         "lingeries",
         "milfs",
         "wanks",
         "orals",
         "suckings",
         "straddles",
         "orgasms",
         "sluts",
         "cummings",
         "cunts",
         "bastards",
         "faggots",
         "niggers",
         "niggas",
         "poops",
         "smegmas",
         "spunks",
         "turds",
         "twats",
         "whores",
         "negro",
         "negros",
         "nipple",
         "nipples",
         "nakey",
         "nakeyd",
         "genitalia",
         "genitals",
         "preteen",
         "preteens",
         "blood",
         "decaying",
         "murdered",
         "killed",
         "brulalized",
         "nudism",
         "naturist",
         "pussylicking",
         "fanny",
         "crap",
         "hoe",
         "soused",
         "cunnie",
         "eat my ass",
         "lesbo",
         "shittings",
         "violet wand",
         "horny",
         "ejaculated",
         "motherfuckin",
         "picka",
         "nob",
         "fukken",
         "vorarephilia",
         "cockface",
         "sleaze",
         "clitface",
         "fagit",
         "s.o.b.",
         "thug",
         "assmunch",
         "jackoff",
         "fuchah",
         "butthole",
         "shipal",
         "rautenberg",
         "h00r",
         "pollock",
         "shagging",
         "fucknut",
         "undies",
         "queer",
         "fux",
         "strap on",
         "hitler",
         "horniest",
         "x-rated2g1c",
         "trashy",
         "4r5e",
         "puuke",
         "vag",
         "kurac",
         "wh0re",
         "shitfuck",
         "fart",
         "valium",
         "moolie",
         "tittywank",
         "sx",
         "pisof",
         "shitblimp",
         "polack",
         "faigt",
         "murder",
         "kinbaku",
         "fistfuckings",
         "v14gra",
         "fistfucker",
         "punkass",
         "jack off",
         "pimp",
         "niggah",
         "whored",
         "cuming",
         "drunk",
         "sh1tz",
         "asholes",
         "fcuking",
         "shibary",
         "pedo",
         "gaywad",
         "bullet vibe",
         "fisted",
         "female squirting",
         "poo",
         "pot",
         "throating",
         "vag1na",
         "donkeyribber",
         "asswipe",
         "hooker",
         "orgasim",
         "assclown",
         "fagging",
         "panooch",
         "cockmaster",
         "whoring",
         "fingerbang",
         "fucknugget",
         "cyberfuc",
         "feg",
         "shit-stain",
         "mthrfucker",
         "pornography",
         "cyberfucking",
         "shit-bag",
         "seduce",
         "opiate",
         "sexxx",
         "quim",
         "shit-dick",
         "injun",
         "smutty",
         "sumofabiatch",
         "shytty",
         "mof0",
         "incest",
         "b!tch",
         "titt",
         "fucktrophy",
         "xx",
         "mother fucker",
         "peckerhead",
         "teez",
         "slutkiss",
         "splooge",
         "puto",
         "bellend",
         "ninny",
         "titi",
         "schlong",
         "enema",
         "inbred",
         "scank",
         "shitbrain",
         "tranny",
         "bbw",
         "stoned",
         "camslut",
         "fuckin",
         "queerhole",
         "faig",
         "knobed",
         "autoerotic",
         "shiznit",
         "opium",
         "herpy",
         "skrib",
         "brown shower",
         "brunette action",
         "skankey",
         "hiv",
         "assface",
         "tainted love",
         "piece of shit",
         "kunilingus",
         "dilld0",
         "vullva",
         "freex",
         "fuckass",
         "pubic",
         "dickhole",
         "nads",
         "dumshit",
         "buttcheeks",
         "niigr",
         "fuckingshitmotherfucker",
         "sh1ts",
         "stfu",
         "douche",
         "gaytard",
         "snowballing",
         "fecker",
         "s hit",
         "neonazi",
         "cnut",
         "pisses",
         "jerk-off",
         "sausagequeen",
         "howtomurdep",
         "uzi",
         "doggin",
         "shit-house",
         "cazzo",
         "pissers",
         "shitting",
         "pthc",
         "swinger",
         "shit-brain",
         "penus",
         "dp action",
         "cummer",
         "poop chute",
         "l3itch",
         "pimpis",
         "testee",
         "cuntrag",
         "undressing",
         "m0fo",
         "pr1k",
         "asslicker",
         "leper",
         "puss",
         "nutbutter",
         "jackass",
         "big knockers",
         "a55",
         "lemon party",
         "oriface",
         "stripclub",
         "twatty",
         "mothafucking",
         "rumprammer",
         "topless",
         "foot fetish",
         "yaoi",
         "shit-breath",
         "gfy",
         "cyalis",
         "kondum",
         "dog-fucker",
         "nudity",
         "masterbating",
         "whorehouse",
         "bimbos",
         "thundercunt",
         "screwing",
         "white power",
         "ball kicking",
         "wrinkled starfish",
         "retarded",
         "knobjokey",
         "bunny fucker",
         "ritard",
         "dykes",
         "enculer",
         "mafugly",
         "slutbag",
         "ovum",
         "peepee",
         "numbnuts",
         "klan",
         "yiffy",
         "voyeur",
         "towelhead",
         "xrated",
         "nob jokey",
         "dickjuice",
         "poon",
         "scheiss",
         "whoreface",
         "cunnilingus",
         "knobhead",
         "mams",
         "kiunt",
         "asshead",
         "hooch",
         "pedophilia",
         "smeg",
         "gaylord",
         "assbanged",
         "frotting",
         "mothafuker",
         "assholz",
         "zoophilia",
         "bich",
         "shit-eating",
         "pantie",
         "paska",
         "eatadick",
         "boffing",
         "shitbag",
         "phukking",
         "pisspig",
         "urine",
         "peinus",
         "piss pig",
         "fingerfuck",
         "arschloch",
         "muther",
         "tittie5",
         "apeshit",
         "gaybor",
         "goatse",
         "god damn",
         "muthafukkah",
         "cocksukka",
         "chocolate rosebuds",
         "cumdumpster",
         "asssucker",
         "uterus",
         "shitbreath",
         "fack",
         "muthafuckker",
         "scat",
         "pierdol",
         "motherfucking",
         "huevon",
         "gaysex",
         "erotic",
         "punta",
         "phalli",
         "birdlock",
         "nutsack",
         "mothafucka",
         "shit-cunt",
         "pakie",
         "ass-hat",
         "jerkoff",
         "mothafukker",
         "ballbag",
         "b1tch",
         "pubes",
         "pises",
         "motherfukkah",
         "fucker",
         "jiggaboo",
         "asswhole",
         "kunt",
         "f_u_c_k",
         "rimjaw",
         "cuntz",
         "cocknugget",
         "lust",
         "shaggin",
         "nobhead",
         "n1gger",
         "scum",
         "cocksmith",
         "shag",
         "kike",
         "nazi",
         "shitt",
         "lezzies",
         "jap",
         "orally",
         "hardcoresex",
         "punanny",
         "panty",
         "suck",
         "douchey",
         "pimmel",
         "cockburger",
         "swastika",
         "toke",
         "nawashi",
         "fags",
         "how to murder",
         "gaygirl",
         "yury",
         "jerk",
         "klootzak",
         "cabron",
         "humping",
         "d1ck",
         "hemp",
         "flikker",
         "doochbag",
         "gaybob",
         "cok",
         "hoare",
         "sissy",
         "hooters",
         "vagiina",
         "assfuck",
         "shitspitter",
         "faggit",
         "shitfucker",
         "tushy",
         "fuks",
         "teets",
         "ghay",
         "fanculo",
         "fuckings",
         "carpetmuncher",
         "pusse",
         "gtfo",
         "daygo",
         "scrot",
         "fukka",
         "poontang",
         "hot chick",
         "hoar",
         "schizo",
         "black cock",
         "scrog",
         "masterbat3",
         "ball licking",
         "dinks",
         "skank",
         "two girls one cup",
         "muie",
         "cyberfuckers",
         "huge fat",
         "lesbian",
         "sadism",
         "farted",
         "assbag",
         "pr1c",
         "dvda",
         "nobjokey",
         "ecchi",
         "rectus",
         "punky",
         "gae",
         "flipping",
         "bitching",
         "hardcore",
         "playboy",
         "ash0le",
         "coprophilia",
         "kkk",
         "cornhole",
         "double penetration",
         "pissflap",
         "aryan",
         "slutdumper",
         "choad",
         "poonani",
         "kumming",
         "cocksuck",
         "cuntlicker",
         "raping",
         "motherfuckka",
         "pis",
         "wad",
         "jelly donut",
         "fucking",
         "fisting",
         "urethra play",
         "poontsee",
         "god-damned",
         "faget",
         "dike",
         "fagots",
         "bimbo",
         "wanky",
         "faggitt",
         "group sex",
         "goatcx",
         "missionary position",
         "bi7ch",
         "phonesex",
         "jackhole",
         "shit-fit",
         "extacy",
         "penisbreath",
         "farting",
         "ahole",
         "masterbation",
         "jerk off",
         "pissing",
         "len",
         "muthafuker",
         "qweers",
         "wigger",
         "balls",
         "motha",
         "b17ch",
         "cockbite",
         "junky",
         "cocksuka",
         "cocksmoker",
         "scrud",
         "dommes",
         "kanker",
         "b00bs",
         "assmuncher",
         "damn",
         "cockmunch",
         "wtf",
         "muffpuff",
         "prude",
         "ruski",
         "enlargement",
         "penuus",
         "tight white",
         "phuking",
         "fannybandit",
         "shit-bagger",
         "vulgar",
         "kyke",
         "fistfuckers",
         "testis",
         "assbite",
         "futkretzn",
         "faggs",
         "eunuch",
         "f4nny",
         "mofo",
         "amcik",
         "fistfucked",
         "poopchute",
         "fistfucking",
         "farty",
         "breasts",
         "mutherfucking",
         "pigfucker",
         "pizda",
         "knobead",
         "hoor",
         "hoore",
         "poonany",
         "@$$",
         "penas",
         "herpes",
         "mothafuckers",
         "camgirl",
         "t1tt1e5",
         "pusies",
         "orifiss",
         "honky",
         "snuff",
         "leather straight jacket",
         "chinc",
         "shithole",
         "honkey",
         "muthrfucking",
         "slutz",
         "blow job",
         "shite",
         "assshole",
         "hussy",
         "sob",
         "whorehopper",
         "cipa",
         "cocksucked",
         "fux0r",
         "coprolagnia",
         "jiz",
         "bi+ch",
         "shitty",
         "willy",
         "bitchin",
         "fagz",
         "junkie",
         "hootch",
         "fuckhole",
         "assmonkey",
         "pecker",
         "masterbaiter",
         "ejaculating",
         "fuckheads",
         "escort",
         "mothafucker",
         "panties",
         "kwif",
         "tush",
         "nasty",
         "hymen",
         "fuckup",
         "dingleberries",
         "pleasure chest",
         "fuckhead",
         "ayir",
         "pricks",
         "lusty",
         "gays",
         "tard",
         "pusy",
         "sodomy",
         "mothafuckin",
         "qahbeh",
         "kill",
         "foad",
         "shamedame",
         "shit-head",
         "pegging",
         "h0r",
         "dog style",
         "doggie style",
         "grope",
         "dickmonger",
         "dominatricks",
         "goddam",
         "shibari",
         "fudge packer",
         "hebe",
         "qweerz",
         "erect",
         "masterbate",
         "reverse cowgirl",
         "venus mound",
         "doggy style",
         "doggystyle",
         "godamn",
         "whoar",
         "cumguzzler",
         "pillu",
         "goregasm",
         "dickweed",
         "wedgie",
         "twatlips",
         "asswad",
         "ejakulate",
         "pula",
         "twunter",
         "fagbag",
         "assbang",
         "motherfukker",
         "mouliewop",
         "pule",
         "ficken",
         "perse",
         "dominatrix",
         "bollocks",
         "dumbasses",
         "jailbait",
         "dego",
         "baby batter",
         "nobjocky",
         "shitter",
         "pissin",
         "camel toe",
         "cl1t",
         "smut",
         "sh1ter",
         "femdom",
         "nad",
         "phuck",
         "dipshit",
         "m0f0",
         "phuq",
         "jism",
         "testical",
         "rectal",
         "loins",
         "lipshits",
         "kooches",
         "asanchez",
         "vaj1na",
         "fecal",
         "kraut",
         "pornos",
         "slanteye",
         "heroin",
         "hookah",
         "dingleberry",
         "nymphomania",
         "loin",
         "teat",
         "goo girl",
         "weewee",
         "dupa",
         "essohbee",
         "basterds",
         "skanck",
         "nappy",
         "dild0s",
         "brown showers",
         "phuker",
         "mothafucks",
         "tampon",
         "sodom",
         "hard core",
         "f u c k",
         "schmuck",
         "lezbo",
         "pastie",
         "packy",
         "ekto",
         "bondage",
         "crotch",
         "bloody",
         "phuc",
         "shited",
         "cockhead",
         "vjayjay",
         "feltcher",
         "queero",
         "sultry women",
         "arrse",
         "fukin",
         "masturbat",
         "titties",
         "hui",
         "m45terbate",
         "fukkin",
         "alaskan pipeline",
         "fucked",
         "dammit",
         "shit-spitter",
         "toots",
         "big black",
         "pr0n",
         "gooks",
         "beastility",
         "homoey",
         "dumass",
         "gonads",
         "blumpkin",
         "sh1tter",
         "ovums",
         "terd",
         "bastardo",
         "pising",
         "t1tties",
         "barenaked",
         "dookie",
         "weirdo",
         "s&amp;m",
         "fubar",
         "rapist",
         "ass-fucker",
         "shithead",
         "pr1ck",
         "dickface",
         "kikes",
         "style doggy",
         "shit-load",
         "2 girls 1 cup",
         "va-j-j",
         "wetback",
         "fitt",
         "queaf",
         "cockmuncher",
         "nastt",
         "fook",
         "fuckme",
         "racy",
         "sharmute",
         "paky",
         "assh0le",
         "feltch",
         "assfucker",
         "gayz",
         "fuckers",
         "peeenus",
         "menstruate",
         "cock-sucker",
         "big tits",
         "shaved beaver",
         "wop",
         "fukah",
         "pissed",
         "orospu",
         "pasty",
         "teste",
         "nig",
         "wench",
         "make me come",
         "snatch",
         "dirsa",
         "masokist",
         "frigg",
         "beastiality",
         "gspot",
         "ma5terbate",
         "f u c k e r",
         "2g1c",
         "butt-pirate",
         "foobar",
         "twink",
         "fucktards",
         "felcher",
         "flamer",
         "monkleigh",
         "motherfukah",
         "sexx",
         "ejaculatings",
         "cockjockey",
         "dicksucker",
         "fuken",
         "testicle",
         "phone sex",
         "bunghole",
         "bukake",
         "buttwipe",
         "testes",
         "nambla",
         "lusting",
         "mutha",
         "suicide girls",
         "scag",
         "punany",
         "tea bagging",
         "pussyfart",
         "fagot",
         "taste my",
         "jizzed",
         "gangbanged",
         "pole smoker",
         "arsehole",
         "cums",
         "shit-ass",
         "ekrem",
         "fuckyomama",
         "booooooobs",
         "jail bait",
         "rump",
         "fingerfucker",
         "sharmuta",
         "dickweasel",
         "motherfuckers",
         "feces",
         "coons",
         "cocknose",
         "urophilia",
         "ejaculation",
         "asspirate",
         "bangbros",
         "fistfuck",
         "rimjob",
         "blonde action",
         "fuxor",
         "jiss",
         "pedophile",
         "erotism",
         "dilld0s",
         "sniper",
         "cockknoker",
         "gai",
         "shagger",
         "nooky",
         "leather restraint",
         "shitstain",
         "muff diver",
         "cockmonkey",
         "spooge",
         "babeland",
         "bastardz",
         "juggs",
         "wazoo",
         "cuntface",
         "g-spot",
         "cyberfuck",
         "cnts",
         "shitfull",
         "sadist",
         "hot carl",
         "doosh",
         "shaved pussy",
         "bestiality",
         "ho",
         "assgoblin",
         "jigaboo",
         "faen",
         "fukwhit",
         "darkie",
         "motherfuck",
         "schlampe",
         "scroat",
         "floozy",
         "hoer",
         "ponyplay",
         "teabagging",
         "bung hole",
         "vixen",
         "wang",
         "pubis",
         "cuntlicking",
         "twinkie",
         "gooch",
         "clit",
         "heeb",
         "willies",
         "raped",
         "tw4t",
         "skankee",
         "coksucka",
         "strip club",
         "bampot",
         "pen1s",
         "va1jina",
         "phukked",
         "boiolas",
         "kummer",
         "niggle",
         "shit-pot",
         "paki",
         "fisty",
         "motherfucked",
         "assbandit",
         "cleveland steamer",
         "shitface",
         "barely legal",
         "stiffy",
         "masterbations",
         "m-fucking",
         "one guy one jar",
         "sh!+",
         "nimrod",
         "nigg4h",
         "wh00r",
         "potty",
         "guro",
         "recktum",
         "guiena",
         "sucks",
         "chraa",
         "asscock",
         "goddamned",
         "fuker",
         "muthafecker",
         "shitey",
         "fagged",
         "masturbating",
         "kinky",
         "btch",
         "asshopper",
         "knobjocky",
         "fondle",
         "assfukka",
         "jisim",
         "sodomize",
         "cunilingus",
         "w00se",
         "howtokill",
         "semen",
         "kurwa",
         "g00k",
         "girl on",
         "clover clamps",
         "fukwit",
         "perversion",
         "fooker",
         "nimphomania",
         "shiteater",
         "circlejerk",
         "shitheel",
         "shitz",
         "tinkle",
         "goodpoop",
         "pissflaps",
         "ball gravy",
         "n1gr",
         "lube",
         "giant cock",
         "pron",
         "fuckwad",
         "weenie",
         "weiner",
         "tongue in a",
         "double dong",
         "h4x0r",
         "shit-hole",
         "gigolo",
         "frigga",
         "mothafukkah",
         "rtard",
         "shitted",
         "camwhore",
         "masterbat*",
         "andskota",
         "dickmilk",
         "gayboy",
         "queers",
         "guido",
         "jerked",
         "pussypounder",
         "boooobs",
         "tittiefucker",
         "kusi",
         "bitcher",
         "nsfw images",
         "penial",
         "carpet muncher",
         "motherfucks",
         "douchebag",
         "shitters",
         "herp",
         "mibun",
         "shitbagger",
         "alabama hot pocket",
         "ghey",
         "c0k",
         "big breasts",
         "shiteating",
         "sh!t",
         "dopey",
         "polak",
         "dlck",
         "girls gone wild",
         "shity",
         "glans",
         "mthrfucking",
         "gangbangs",
         "ball sucking",
         "prince albert piercing",
         "basterdz",
         "deep throat",
         "whoralicious",
         "skanky",
         "lezbians",
         "mothafucked",
         "niglet",
         "cawk",
         "santorum",
         "kootch",
         "fingerfucks",
         "bitchers",
         "kuksuger",
         "peenus",
         "wanker",
         "fuckmeat",
         "twathead",
         "sexo",
         "bollox",
         "mothafuckaz",
         "golden shower",
         "screw",
         "p0rn",
         "skag",
         "muthafukker",
         "spiks",
         "d4mn",
         "fcuk",
         "motherfucker",
         "paedophile",
         "polac",
         "shitings",
         "shitcunt",
         "hotsex",
         "lech",
         "nigg3r",
         "fuckpuppet",
         "sexual",
         "baby juice",
         "cox",
         "shrimping",
         "muthafukah",
         "whitey",
         "shit-face",
         "penisfucker",
         "extasy",
         "assrammer",
         "dild0",
         "mtherfucker",
         "spik",
         "kock",
         "retard",
         "scantily",
         "sucked",
         "strapon",
         "cumslut",
         "gokkun",
         "beaners",
         "ejaculate",
         "renob",
         "fartknocker",
         "dong",
         "gaydo",
         "goddamn",
         "cocksucker",
         "anilingus",
         "pcp",
         "gook",
         "ball gag",
         "5hit",
         "orgasum",
         "dickwad",
         "donkey punch",
         "orgies",
         "cumbubble",
         "dirty pillows",
         "menses",
         "cockmongruel",
         "ma5terb8",
         "shitass",
         "xxx",
         "vigra",
         "pisser",
         "fukker",
         "tawdry",
         "futanary",
         "lezbos",
         "dirty sanchez",
         "douchebags",
         "scrote",
         "raper",
         "assh0lez",
         "cumjockey",
         "gayass",
         "titfuck",
         "maxi",
         "daterape",
         "felch",
         "beastial",
         "pms",
         "transsexual",
         "blow your load",
         "tosser",
         "cyberfucker",
         "hand job",
         "screwed",
         "futanari",
         "masterbat",
         "pedophiliac",
         "dink",
         "jiggerboo",
         "flogthelog",
         "bassterds",
         "packi",
         "fanyy",
         "mamhoon",
         "cockshit",
         "fatass",
         "queerbait",
         "meth",
         "chuj",
         "kyrpa",
         "nepesaurio",
         "fukking",
         "quicky",
         "nazism",
         "pillowbiter",
         "lezbian",
         "date rape",
         "ovary",
         "moron",
         "pinko",
         "rosy palm",
         "lesbos",
         "reich",
         "nigg",
         "muschi",
         "fotze",
         "c0cksucker",
         "dickslap",
         "dendrophilia",
         "porno",
         "homoerotic",
         "girl on top",
         "bch",
         "beaver cleaver",
         "raging boner",
         "phallic",
         "beaner",
         "paddy",
         "goddammit",
         "penetrate",
         "tied up",
         "bestial",
         "motherfuker",
         "fannyflaps",
         "lolita",
         "duche",
         "cocksucking",
         "busty",
         "gay sex",
         "hooter",
         "mothafuckas",
         "yellow showers",
         "shit-faced",
         "fuk",
         "kooch",
         "masterb8",
         "schaffer",
         "raunch",
         "cunthole",
         "menage a trois",
         "peeenusss",
         "tittyfucker",
         "shitpot",
         "cocksucks",
         "vomit",
         "shiz",
         "wet dream",
         "urinal",
         "mulkku",
         "gangbang",
         "dickbeater",
         "niggaz",
         "polesmoker",
         "strip",
         "cooter",
         "wrapping men",
         "muffdiving",
         "tribadism",
         "shyte",
         "lesbians",
         "shit-heel",
         "tub girl",
         "gassyass",
         "eathairpie",
         "pussies",
         "gey",
         "areole",
         "asshat",
         "buttpirate",
         "shiting",
         "pissoff",
         "h0re",
         "massterbait",
         "fagg",
         "cokmuncher",
         "motherfuckings",
         "lez",
         "molest",
         "kinkyJesus",
         "rum",
         "helvete",
         "lezzian",
         "lipshitz",
         "fagtard",
         "pedobear",
         "masochist",
         "booty call",
         "rectum",
         "humped",
         "shi+",
         "fuckface",
         "slutty",
         "acrotomophilia",
         "figging",
         "lezzie",
         "needthedick",
         "pussi",
         "clusterfuck",
         "kum",
         "how to kill",
         "god-dam",
         "shitdick",
         "strappado",
         "orgasims",
         "arian",
         "dickwod",
         "skeet",
         "ejaculates",
         "dominatrics",
         "ass-pirate",
         "hardon",
         "lovemaking",
         "puuker",
         "fcuker",
         "mo-fo",
         "shittiest",
         "shota",
         "mutherfucker",
         "phuked",
         "spread legs",
         "nigur",
         "fukkah",
         "fuck buttons",
         "reetard",
         "w0p",
         "fuckwhit",
         "merd",
         "gonad",
         "queef",
         "rusty trombone",
         "clits",
         "twunt",
         "a_s_s",
         "booobs",
         "doggiestyle",
         "son-of-a-bitch",
         "cockmongler",
         "coochy",
         "masstrbate",
         "orgasmic",
         "v1gra",
         "s_h_i_t",
         "muthafucker",
         "nig nog",
         "beaver lips",
         "kawk",
         "knobz",
         "masstrbait",
         "blue waffle",
         "souse",
         "one cup two girls",
         "jizm",
         "gay",
         "muffdiver",
         "cyberfucked",
         "heshe",
         "menstruation",
         "omorashi",
         "massa",
         "fannyfucker",
         "queerz",
         "hentai",
         "intercourse",
         "spic",
         "rosy palm and her 5 sisters",
         "puta",
         "shitload",
         "shemale",
         "buceta",
         "ganja",
         "splooge moose",
         "titty",
         "fuckwit",
         "dry hump",
         "cumtart",
         "napalm",
         "shithouse",
         "pussee",
         "buttmunch",
         "phuks",
         "phukker",
         "bastinado",
         "chink",
         "orifice",
         "orafis",
         "fucktard",
         "godamnit",
         "kumer",
         "mothafuck",
         "kums",
         "qweir",
         "bulldyke",
         "footjob",
         "rape",
         "scissoring",
         "hamflap",
         "ar5e",
         "pee",
         "booooobs",
         "fuckbitch",
         "spick",
         "prig",
         "boobie",
         "fingerfucking",
         "master-bate",
         "lezzy",
         "titwank",
         "ball sack",
         "sonofabitch",
         "motherfucka",
         "octopussy",
         "whiz",
         "phuk",
         "auto erotic",
         "mound of venus",
         "knobbing",
         "jack-off",
         "mr hands",
         "ejackulate",
         "fucka",
         "cum",
         "shitfaced",
         "felatio",
         "fucktoy",
         "fuckoff",
         "chode",
         "kondums",
         "penetration",
         "raghead",
         "cunillingus",
         "l3i+ch",
         "whorealicious",
         "dyke",
         "pisin",
         "hore",
         "hobag",
         "upskirt",
         "n1gga",
         "knulle",
         "assbanger",
         "fingerfucked",
         "dogging",
         "blonde on blonde action",
         "tittyfuck",
         "gringo",
         "kinkster",
         "kuntz",
         "cntz",
         "rimming",
         "dziwka",
         "coochie",
         "dumbshit",
         "fxck",
         "vajina",
         "fingerfuckers",
         "tubgirl",
         "dolcett",
         "sleazy",
         "cuntlick",
         "niiger",
         "azzhole",
         "c0ck",
         "asslick",
         "mothafuckings",
         "poof",
         "japs",
         "muthafuckaz",
         "fagg1t",
         "male squirting",
         "woose",
         "peyote",
         "reefer",
         "asscracker",
         "nympho",
         "fistfucks",
         "ugly",
         "stroke",
         "womb",
         "pussypalace",
         "minge",
         "fag1t",
         "dickbag",
         "h0ar",
         "shitfit",
         "5h1t",
         "penile",
         "packie",
         "gang bang",
         "goldenshower",
         "slutbucket",
         "assjacker"
     ]

    
    static func isPromptSafe(userPrompt:String) -> Bool {
        let forbiddenKeywords : [String] = [
            // General nudity & explicit content
            "nude", "porn", "sexy", "18+", "xxx", "erotic", "provocative", "explicit",
            "sexual content", "naked", "sensual", "adult content", "hot photos", "pornographic",
            "nude images", "obscene", "vulgar", "strip", "seductive", "hardcore", "softcore",
            
            // Inappropriate interactions with minors
            "touching children", "caressing child", "child abuse", "child grooming",
            "sexual contact with minors", "child exploitation", "online child enticement",
            "child pornography", "pedophilia", "grooming minors", "chat with minors",
            "exploiting minors", "sexual blackmail", "child sex trafficking",
            "selling children", "buying children", "child rape", "underage sex",
            "molesting children", "child seduction", "inappropriate conversations with kids",
            
            // See-through clothing & sheer outfits
            "see-through", "transparent fabric", "sheer fabric", "thin fabric",
            "see-through lingerie", "sheer lingerie", "sheer bra", "see-through bra",
            "transparent bra", "see-through dress", "sheer dress", "transparent dress",
            "wet shirt", "nipple visible", "clothing wet", "clothing sticking to skin",
            "exposed nipples", "see-through outfit", "mesh lingerie", "mesh outfit",
            "transparent top", "revealing mesh", "thin silk", "wet fabric",
            "body visible through fabric", "partially see-through", "translucent fabric",
            
            // Breast exposure & unbuttoning clothes
            "bare breasts", "topless", "exposed chest", "open shirt", "unbuttoned shirt",
            "shirt pulled open", "breasts visible", "shirt lifted", "shirt opened",
            "revealing cleavage", "deep cleavage", "open blouse", "shirt undone",
            "boobs visible", "bust exposure", "breast outline", "nipples showing",
            "exposed nipples", "undressing", "taking off shirt", "pulling shirt",
            "shirt off", "holding shirt open", "unzipped top", "unzipping shirt",
            
            // Sexual activities & explicit actions
            "sexual activity", "intercourse", "having sex", "making love", "orgasm",
            "penetration", "naughty pose", "striptease", "sensual dance", "sex position",
            "sex scene", "simulated sex", "seductive touching", "intimate touching",
            "provocative licking", "foreplay", "kissing breasts", "licking lips sexually",
            "sensual touching", "erotic massage", "naughty pose", "spreading legs",
            "sexual roleplay", "erotic scene", "naughty cosplay", "dominatrix role",
            "submissive pose", "nude couple", "explicit action",
            
            // Public indecency & inappropriate exposure
            "exposed in public", "nude in public", "flashing", "public nudity",
            "inappropriate in public", "skimpy outfit in public", "revealing outfit in public",
            "public undressing", "wardrobe malfunction", "bare butt", "butt crack",
            "scandalous clothing", "inappropriate exposure", "revealing too much",
            
            // Other revealing clothing & provocative attire
            "underboob", "sideboob", "cleavage", "sexual pose", "bra", "panties",
            "bikini", "underwear", "latex outfit", "dominatrix", "fetish", "corset",
            "fishnet", "swimsuit mode", "leather outfit",
            
            // Liquids & effects that simulate explicit content
            "wet", "glowing liquid", "body paint", "oil on body", "splattered", "sticky",
            "shiny skin", "sweaty", "glistening", "dripping", "spilled liquid",
            
            // Inappropriate body poses & expressions
            "bending over", "suggestive pose", "legs spread", "aroused", "moaning",
            "lips biting", "tongue out", "teasing", "tempting look", "sultry", "gaze",
            "bedroom eyes", "submissive pose", "dominant pose",
            
            //orther
            "dirty woman","0 years old","1 years old","2 years old","3 years old","4 years old",
            "5 years old","6 years old","7 years old","8 years old","9 years old","10 years old",
            "11 years old","12 years old","13 years old","14 years old","15 years old","16 years old",
            "17 years old","0 yo","1 yo","2 yo","3 yo","4 yo","5 yo","6 yo","7 yo","8 yo","9 yo","10 yo",
            "11 yo","12 yo","13 yo","14 yo","15 yo","16 yo","17 yo","painfully killed","cock","deepthroat",
            "dick","cumshot","wet","fuck","sperm","naked","ass","tits","fingering","masturbate","bitch","blowjob",
            "prostitute","shit","bullshit","dumbass","dickhead","pussy","piss","asshole","boobs","butt","booty","dildo",
            "erection","foreskin","gag","handjob","nude","penis","porn","vibrator","viagra","virgin","vagina","vulva","threesome",
            "orgy","bdsm","hickey","condom","sexting","testicles","anal","bareback","bukkake","creampie","stripper","strap-on",
            "clitoris","cowgirl","fleshlight","contraceptive","lingerie","milf","wank","oral","sucking","straddle","orgasm","slut",
            "cumming","ode","prick","cunt","bastard","faggot","anus","sex","arse","ballsack","biatch","bollock","bollok","boner","boob",
            "bugger","buttplug","coon","fag","feck","fellate","fellatio","felching","fuсk","fudgepacker","homo","jizz","knobend","labia",
            "lmao","lmfao","muff","nigger","nigga","poop","pube","scrotum","sh1t","smegma","spunk","tit","turd","twat","whore","cocks",
            "deepthroats","dicks","cumshots","fucks","sperms","asses","masturbation","bitches","blowjobs","prostitutes","shits","bullshits",
            "dickheads","pussys","pisssing","assholes","butts","dildos","erections","foreskins","gags","handjobs","nudes","penises","vibrators",
            "virgins","vaginas","vulvas","threesomes","orgys","bdsms","hickeys","condoms","sextings","anals","barebacks","bukkakes","creampies",
            "strippers","strap-ons","clitoriss","cowgirls","fleshlights","contraceptives","lingeries","milfs","wanks","orals","suckings","straddles",
            "orgasms","sluts","cummings","cunts","bastards","faggots","niggers","niggas","poops","smegmas","spunks","turds","twats","whores","negro",
            "negros","nipple","nipples","nakey","nakeyd","genitalia","genitals","preteen","preteens","blood","decaying","murdered","killed","brulalized",
            "nudism","naturist","pussylicking","fanny","crap","hoe","soused","cunnie","eat my ass","lesbo","shittings","violet wand","horny","ejaculated",
            "motherfuckin","picka","nob","fukken","vorarephilia","cockface","sleaze","clitface","fagit","s.o.b.","thug","assmunch","jackoff","fuchah","butthole",
            "shipal","rautenberg","h00r","pollock","shagging","fucknut","undies","queer","fux","strap on","hitler","horniest","x-rated2g1c","trashy","4r5e","puuke",
            "vag","kurac","wh0re","shitfuck","fart","valium","moolie","tittywank","sx","pisof","shitblimp","polack","faigt","murder","kinbaku","fistfuckings","v14gra",
            "fistfucker","punkass","jack off","pimp","niggah","whored","cuming","drunk","sh1tz","asholes","fcuking","shibary","pedo","gaywad","bullet vibe","fisted",
            "female squirting","poo","pot","throating","vag1na","donkeyribber","asswipe","hooker","orgasim","assclown","fagging","panooch","cockmaster","whoring",
            "fingerbang","fucknugget","cyberfuc","feg","shit-stain","mthrfucker","pornography","cyberfucking","shit-bag","seduce","opiate","sexxx","quim","shit-dick",
            "injun","smutty","sumofabiatch","shytty","mof0","incest","b!tch","titt","fucktrophy","xx","mother fucker","peckerhead","teez","slutkiss","splooge","puto",
            "bellend","ninny","titi","schlong","enema","inbred","scank","shitbrain","tranny","bbw","stoned","camslut","fuckin","queerhole","faig","knobed","autoerotic",
            "shiznit","opium","herpy","skrib","brown shower","brunette action","skankey","hiv","assface","tainted love","piece of shit","kunilingus","dilld0","vullva",
            "freex","fuckass","pubic","dickhole","nads","dumshit","buttcheeks","niigr","fuckingshitmotherfucker","sh1ts","stfu","douche","gaytard","snowballing","fecker",
            "s hit","neonazi","cnut","pisses","jerk-off","sausagequeen","howtomurdep","uzi","doggin","shit-house","cazzo","pissers","shitting","pthc","swinger","shit-brain",
            "penus","dp action","cummer","poop chute","l3itch","pimpis","testee","cuntrag","undressing","m0fo","pr1k","asslicker","leper","puss","nutbutter","jackass",
            "big knockers","a55","lemon party","oriface","stripclub","twatty","mothafucking","rumprammer","topless","foot fetish","yaoi","shit-breath","gfy","cyalis","kondum",
            "dog-fucker","nudity","masterbating","whorehouse","bimbos","thundercunt","screwing","white power","ball kicking","wrinkled starfish","retarded","knobjokey",
            "bunny fucker","ritard","dykes","enculer","mafugly","slutbag","ovum","peepee","numbnuts","klan","yiffy","voyeur","towelhead","xrated","nob jokey","dickjuice",
            "poon","scheiss","whoreface","cunnilingus","knobhead","mams","kiunt","asshead","hooch","pedophilia","smeg","gaylord","assbanged","frotting","mothafuker","assholz",
            "zoophilia","bich","shit-eating","pantie","paska","eatadick","boffing","shitbag","phukking","pisspig","urine","peinus","piss pig","fingerfuck","arschloch","muther",
            "tittie5","apeshit","gaybor","goatse","god damn","muthafukkah","cocksukka","chocolate rosebuds","cumdumpster","asssucker","uterus","shitbreath","fack","muthafuckker","scat",
            "pierdol","motherfucking","huevon","gaysex","erotic","punta","phalli","birdlock","nutsack","mothafucka","shit-cunt","pakie","ass-hat","jerkoff","mothafukker","ballbag",
            "b1tch","pubes","pises","motherfukkah","fucker","jiggaboo","asswhole","kunt","f_u_c_k","rimjaw","cuntz","cocknugget","lust","shaggin","nobhead","n1gger","scum","cocksmith",
            "shag","kike","nazi","shitt","lezzies","jap","orally","hardcoresex","punanny","panty","suck","douchey","pimmel","cockburger","swastika","toke","nawashi","fags","how to murder",
            "gaygirl","yury","jerk","klootzak","cabron","humping","d1ck","hemp","flikker","doochbag","gaybob","cok","hoare","sissy","hooters","vagiina","assfuck","shitspitter","faggit","shitfucker",
            "tushy","fuks","teets","ghay","fanculo","fuckings","carpetmuncher","pusse","gtfo","daygo","scrot","fukka","poontang","hot chick","hoar","schizo","black cock","scrog","masterbat3","ball licking",
            "dinks","skank","two girls one cup","muie","cyberfuckers","huge fat","lesbian","sadism","farted","assbag","pr1c","dvda","nobjokey","ecchi","rectus","punky","gae","flipping","bitching","hardcore",
            "playboy","ash0le","coprophilia","kkk","cornhole","double penetration","pissflap","aryan","slutdumper","choad","poonani","kumming","cocksuck","cuntlicker","raping","motherfuckka","pis","wad",
            "jelly donut","fucking","fisting","urethra play","poontsee","god-damned","faget","dike","fagots","bimbo","wanky","faggitt","group sex","goatcx","missionary position","bi7ch","phonesex","jackhole",
            "shit-fit","extacy","penisbreath","farting","ahole","masterbation","jerk off","pissing","len","muthafuker","qweers","wigger","balls","motha","b17ch","cockbite","junky","cocksuka","cocksmoker","scrud",
            "dommes","kanker","b00bs","assmuncher","damn","cockmunch","wtf","muffpuff","prude","ruski","enlargement","penuus","tight white","phuking","fannybandit","shit-bagger","vulgar","kyke","fistfuckers","testis",
            "assbite","futkretzn","faggs","eunuch","f4nny","mofo","amcik","fistfucked","poopchute","fistfucking","farty","breasts","mutherfucking","pigfucker","pizda","knobead","hoor","hoore","poonany","@$$","penas",
            "herpes","mothafuckers","camgirl","t1tt1e5","pusies","orifiss","honky","snuff","leather straight jacket","chinc","shithole","honkey","muthrfucking","slutz","blow job","shite","assshole","hussy","sob",
            "whorehopper","cipa","cocksucked","fux0r","coprolagnia","jiz","bi+ch","shitty","willy","bitchin","fagz","junkie","hootch","fuckhole","assmonkey","pecker","masterbaiter","ejaculating","fuckheads","escort",
            "mothafucker","panties","kwif","tush","nasty","hymen","fuckup","dingleberries","pleasure chest","fuckhead","ayir","pricks","lusty","gays","tard","pusy","sodomy","mothafuckin","qahbeh","kill","foad","shamedame",
            "shit-head","pegging","h0r","dog style","doggie style","grope","dickmonger","dominatricks","goddam","shibari","fudge packer","hebe","qweerz","erect","masterbate","reverse cowgirl","venus mound","doggy style",
            "doggystyle","godamn","whoar","cumguzzler","pillu","goregasm","dickweed","wedgie","twatlips","asswad","ejakulate","pula","twunter","fagbag","assbang","motherfukker","mouliewop","pule","ficken","perse","dominatrix",
            "bollocks","dumbasses","jailbait","dego","baby batter","nobjocky","shitter","pissin","camel toe","cl1t","smut","sh1ter","femdom","nad","phuck","dipshit","m0f0","phuq","jism","testical","rectal","loins","lipshits",
            "kooches","asanchez","vaj1na","fecal","kraut","pornos","slanteye","heroin","hookah","dingleberry","nymphomania","loin","teat","goo girl","weewee","dupa","essohbee","basterds","skanck","nappy","dild0s","brown showers",
            "phuker","mothafucks","tampon","sodom","hard core","f u c k","schmuck","lezbo","pastie","packy","ekto","bondage","crotch","bloody","phuc","shited","cockhead","vjayjay","feltcher","queero","sultry women","arrse","fukin",
            "masturbat","titties","hui","m45terbate","fukkin","alaskan pipeline","fucked","dammit","shit-spitter","toots","big black","pr0n","gooks","beastility","homoey","dumass","gonads","blumpkin","sh1tter","ovums","terd","bastardo",
            "pising","t1tties","barenaked","dookie","weirdo","s&amp;m","fubar","rapist","ass-fucker","shithead","pr1ck","dickface","kikes","style doggy","shit-load","2 girls 1 cup","va-j-j","wetback","fitt","queaf","cockmuncher","nastt",
            "fook","fuckme","racy","sharmute","paky","assh0le","feltch","assfucker","gayz","fuckers","peeenus","menstruate","cock-sucker","big tits","shaved beaver","wop","fukah","pissed","orospu","pasty","teste","nig","wench","make me come",
            "snatch","dirsa","masokist","frigg","beastiality","gspot","ma5terbate","f u c k e r","2g1c","butt-pirate","foobar","twink","fucktards","felcher","flamer","monkleigh","motherfukah","sexx","ejaculatings","cockjockey","dicksucker",
            "fuken","testicle","phone sex","bunghole","bukake","buttwipe","testes","nambla","lusting","mutha","suicide girls","scag","punany","tea bagging","pussyfart","fagot","taste my","jizzed","gangbanged","pole smoker","arsehole","cums",
            "shit-ass","ekrem","fuckyomama","booooooobs","jail bait","rump","fingerfucker","sharmuta","dickweasel","motherfuckers","feces","coons","cocknose","urophilia","ejaculation","asspirate","bangbros","fistfuck","rimjob","blonde action",
            "fuxor","jiss","pedophile","erotism","dilld0s","sniper","cockknoker","gai","shagger","nooky","leather restraint","shitstain","muff diver","cockmonkey","spooge","babeland","bastardz","juggs","wazoo","cuntface","g-spot","cyberfuck",
            "cnts","shitfull","sadist","hot carl","doosh","shaved pussy","bestiality","ho","assgoblin","jigaboo","faen","fukwhit","darkie","motherfuck","schlampe","scroat","floozy","hoer","ponyplay","teabagging","bung hole","vixen",
            "wang","pubis","cuntlicking","twinkie","gooch","clit","heeb","willies","raped","tw4t","skankee","coksucka","strip club","bampot","pen1s","va1jina","phukked","boiolas","kummer","niggle","shit-pot","paki","fisty","motherfucked",
            "assbandit","cleveland steamer","shitface","barely legal","stiffy","masterbations","m-fucking","one guy one jar","sh!+","nimrod","nigg4h","wh00r","potty","guro","recktum","guiena","sucks","chraa","asscock","goddamned","fuker",
            "muthafecker","shitey","fagged","masturbating","kinky","btch","asshopper","knobjocky","fondle","assfukka","jisim","sodomize","cunilingus","w00se","howtokill","semen","kurwa","g00k","girl on","clover clamps","fukwit","perversion",
            "fooker","nimphomania","shiteater","circlejerk","shitheel","shitz","tinkle","goodpoop","pissflaps","ball gravy","n1gr","lube","giant cock","pron","fuckwad","weenie","weiner","tongue in a","double dong","h4x0r",
            "shit-hole","gigolo","frigga","mothafukkah","rtard","shitted","camwhore","masterbat*","andskota","dickmilk","gayboy","queers","guido","jerked","pussypounder","boooobs","tittiefucker","kusi","bitcher","nsfw images",
            "penial","carpet muncher","motherfucks","douchebag","shitters","herp","mibun","shitbagger","alabama hot pocket","ghey","c0k","big breasts","shiteating","sh!t","dopey","polak","dlck","girls gone wild","shity","glans",
            "mthrfucking","gangbangs","ball sucking","prince albert piercing","basterdz","deep throat","whoralicious","skanky","lezbians","mothafucked","niglet","cawk","santorum","kootch","fingerfucks","bitchers","kuksuger","peenus",
            "wanker","fuckmeat","twathead","sexo","bollox","mothafuckaz","golden shower","screw","p0rn","skag","muthafukker","spiks","d4mn","fcuk","motherfucker","paedophile","polac","shitings","shitcunt","hotsex","lech","nigg3r",
            "fuckpuppet","sexual","baby juice","cox","shrimping","muthafukah","whitey","shit-face","penisfucker","extasy","assrammer","dild0","mtherfucker","spik","kock","retard","scantily","sucked","strapon","cumslut","gokkun","beaners",
            "ejaculate","renob","fartknocker","dong","gaydo","goddamn","cocksucker","anilingus","pcp","gook","ball gag","5hit","orgasum","dickwad","donkey punch","orgies","cumbubble","dirty pillows","menses",
            "cockmongruel","ma5terb8","shitass","xxx","vigra","pisser","fukker","tawdry","futanary","lezbos","dirty sanchez","douchebags","scrote","raper","assh0lez","cumjockey","gayass","titfuck","maxi","daterape",
            "felch","beastial","pms","transsexual","blow your load","tosser","cyberfucker","hand job","screwed","futanari","masterbat","pedophiliac","dink","jiggerboo","flogthelog","bassterds","packi","fanyy","mamhoon",
            "cockshit","fatass","queerbait","meth","chuj","kyrpa","nepesaurio","fukking","quicky","nazism","pillowbiter","lezbian","date rape","ovary","moron","pinko","rosy palm","lesbos","reich","nigg","muschi","fotze",
            "c0cksucker","dickslap","dendrophilia","porno","homoerotic","girl on top","bch","beaver cleaver","raging boner","phallic","beaner","paddy","goddammit","penetrate","tied up","bestial","motherfuker","fannyflaps",
            "lolita","duche","cocksucking","busty","gay sex","hooter","mothafuckas","yellow showers","shit-faced","fuk","kooch","masterb8","schaffer","raunch","cunthole","menage a trois","peeenusss","tittyfucker","shitpot",
            "cocksucks","vomit","shiz","wet dream","urinal","mulkku","gangbang","dickbeater","niggaz","polesmoker","strip","cooter","wrapping men","muffdiving","tribadism","shyte","lesbians","shit-heel","tub girl","gassyass",
            "eathairpie","pussies","gey","areole","asshat","buttpirate","shiting","pissoff","h0re","massterbait","fagg","cokmuncher","motherfuckings","lez","molest","kinkyJesus","rum","helvete","lezzian","lipshitz","fagtard",
            "pedobear","masochist","booty call","rectum","humped","shi+","fuckface","slutty","acrotomophilia","figging","lezzie","needthedick","pussi","clusterfuck","kum","how to kill","god-dam","shitdick","strappado","orgasims",
            "arian","dickwod","skeet","ejaculates","dominatrics","ass-pirate","hardon","lovemaking","puuker","fcuker","mo-fo","shittiest","shota","mutherfucker","phuked","spread legs","nigur","fukkah","fuck buttons","reetard","w0p",
            "fuckwhit","merd","gonad","queef","rusty trombone","clits","twunt","a_s_s","booobs","doggiestyle","son-of-a-bitch","cockmongler","coochy","masstrbate","orgasmic","v1gra","s_h_i_t","muthafucker","nig nog","beaver lips","kawk",
            "knobz","masstrbait","blue waffle","souse","one cup two girls","jizm","gay","muffdiver","cyberfucked","heshe","menstruation","omorashi","massa","fannyfucker","queerz","hentai","intercourse","spic","rosy palm and her 5 sisters",
            "puta","shitload","shemale","buceta","ganja","splooge moose","titty","fuckwit","dry hump","cumtart","napalm","shithouse","pussee","buttmunch","phuks","phukker","bastinado","chink","orifice","orafis","fucktard","godamnit",
            "kumer","mothafuck","kums","qweir","bulldyke","footjob","rape","scissoring","hamflap","ar5e","pee","booooobs","fuckbitch","spick","prig","boobie","fingerfucking","master-bate","lezzy","titwank","ball sack","sonofabitch",
            "motherfucka","octopussy","whiz","phuk","auto erotic","mound of venus","knobbing","jack-off","mr hands","ejackulate","fucka","cum","shitfaced","felatio","fucktoy","fuckoff","chode","kondums","penetration","raghead","cunillingus",
            "l3i+ch","whorealicious","dyke","pisin","hore","hobag","upskirt","n1gga","knulle","assbanger","fingerfucked","dogging","blonde on blonde action","tittyfuck","gringo","kinkster","kuntz","cntz","rimming","dziwka","coochie","dumbshit",
            "fxck","vajina","fingerfuckers","tubgirl","dolcett","sleazy","cuntlick","niiger","azzhole","c0ck","asslick","mothafuckings","poof","japs","muthafuckaz","fagg1t","male squirting","woose","peyote","reefer","asscracker","nympho",
            "fistfucks","ugly","stroke","womb","pussypalace","minge","fag1t","dickbag","h0ar","shitfit","5h1t","penile","packie","gang bang","goldenshower","slutbucket","assjacker"
        ]
        
        let lowerPrompt = userPrompt.lowercased()
        
        return !forbiddenKeywords.contains { keyword in
                let regexPattern = "\\b\(NSRegularExpression.escapedPattern(for: keyword))\\b"
                let regex = try? NSRegularExpression(pattern: regexPattern, options: .caseInsensitive)
                return regex?.firstMatch(in: lowerPrompt, options: [], range: NSRange(location: 0, length: lowerPrompt.utf16.count)) != nil
            }
        
       
    }
}
